<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_GENERIC_ALL</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>10</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>0ac3bcce-d9e6-4101-aa81-2c862f7ac3d5</testSuiteGuid>
   <testCaseLink>
      <guid>7e499d39-ec72-4e34-86ea-b952cd192f25</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GenericSeleniumWebElements/HEROKUAPP/test__user_is_able_to_login_by_basic_auth</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>af32a329-570d-4fe8-99f8-09d154f02dcd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>06492c7c-79aa-4469-b391-86e6d8ec5a24</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1edcf59d-8ad8-4555-9d69-57397b9e7f59</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>955cebdb-a1f9-4697-ac01-94aa6ff3043b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>659ee449-d1da-4371-a96e-1b57e0493dd4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GenericSeleniumWebElements/SELENIUMBASE/test__select_element_on_checkboxes</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>9dacaca4-28d2-4e0b-a381-7a50119a9235</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GenericSeleniumWebElements/SELENIUMBASE/test__hover_dropdown_menu</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>155b8e2e-95c6-4144-be28-014fd6a3e604</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GenericSeleniumWebElements/SELENIUMBASE/test__form_base_element</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7f918cec-c602-4703-ba4a-869f6a477003</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>616ed2f7-90a2-4d14-8bb1-f5979192c62b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>00907fde-bd0a-414d-9d1f-6dcbb469ba0c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b218aa50-569f-45e0-b80a-8da1c06429de</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6af39f3f-137a-4a01-8b0b-48e1b97e05da</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GenericSeleniumWebElements/DEMOQA/test__drag_and_drop_element</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>21e2e268-8d86-4880-89c8-36071d2006cd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GenericSeleniumWebElements/DEMOQA/test__auto_complete</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a014908e-53de-4c49-accf-be94746f793c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>332e6767-33f0-4784-bffd-26cf79c1faf7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>82aee760-83f9-4417-a34b-64620bd52e01</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>43ddd538-36cc-4967-9bf7-75535d53af56</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GenericSeleniumWebElements/HEROKUAPP/test__add_remove_button_element</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>70136f0e-7fbc-4162-bf79-a11f106cf994</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
