<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_LOGIN_FORM</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>10</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>cf688858-4ff2-44c5-b686-b417c2a87b88</testSuiteGuid>
   <testCaseLink>
      <guid>603e070d-88ac-403b-a452-6ed5231ac7fb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DEMOBANK/LoginToApplication/test__login_to_application_with_default_data</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0af8e116-0c68-4cee-a9f3-fcb729fdcaeb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ced0236a-3eee-4158-9643-5b3bd6a876ca</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DEMOBANK/LoginToApplication/test__login_to_application_with_login_shorter_than_eight_chars</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a5779346-d148-4312-bf6a-d1775297d5ea</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c9a24a27-7afb-4584-890b-ed6a00b860f9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a527cc59-eeda-4b2d-8af0-5b9663dac783</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d3ae5e97-1a99-4f77-911d-d312c67f9b69</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DEMOBANK/LoginToApplication/test__login_to_application_with_password_shorter_than_eight_chars</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5b2be1ab-d9cb-4bee-94b2-7cc70945a5ca</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>13bd0c46-fb0c-44d7-9fa9-774c0e0a6e7d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>23092b18-8587-4adc-a7a1-e73972e8a671</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>afc57507-6023-4b49-9760-b88c7df29710</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DEMOBANK/LoginToApplication/test__verify_login_form_step1</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f36c16aa-9c63-4aea-81b5-da232cecf757</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d93f5b5c-9470-4e88-8db8-b5494747fcea</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0be1bc2e-f26a-46a2-94d3-893b6ee07ed3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DEMOBANK/test__verify_login_form_step2</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7e37ba86-5c50-4aad-86b2-a265edda9a75</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
