<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_OPEN_WEATHER_MAP</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>10</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>83d5374b-88c7-46f6-a546-f4ef2e352c68</testSuiteGuid>
   <testCaseLink>
      <guid>de1ea265-96b7-4957-9fae-c58add4fd5a1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/API/OPEN_WEATHER_MAP/test__add_new_station</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dd46815f-4aa0-4c32-8dcd-77779a36d2c6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4dacdebc-5c7d-477c-8d1b-837832b9d873</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e7249b51-eb2b-424d-babb-01708d6704da</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9bac3feb-cbfa-4193-96b8-b1e9805bcba0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>922e4965-36c3-4eb7-a5c6-7bf0708dff5a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>70d59504-e875-4889-8d02-0de236a650b8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1300eada-9284-4a8a-966e-7d796358d35e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/API/OPEN_WEATHER_MAP/test__delete_station_exceed_10</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>26fba960-1798-4c05-a702-dad8cead8416</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2ef3ca6c-4349-426e-833c-07a58727500f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a2150818-5690-4b96-9100-4476ba6a16aa</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/API/OPEN_WEATHER_MAP/test__delete_station__not_found</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7b05181e-df0d-4332-853e-fc70bd256eb2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dd1e7428-abbd-4952-a2a7-cfdac1558136</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8348051d-9f34-4404-a24f-bc53dceae56d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dbfd8cce-47d6-48fb-bbfc-0b08b7a4e8bf</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8f0ed030-2fd5-46a9-8a34-eedfce4ece4d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/API/OPEN_WEATHER_MAP/test__download_station_list</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>522d701c-c8d8-4708-8e5d-28a81c8ebdf3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2faa2f7d-c0c9-40d4-8b55-975af9e34ec3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/API/OPEN_WEATHER_MAP/test__get_station_data_by_id</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0eeade87-9a58-4116-9f5a-b13cdcc03a89</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ca8ad5db-5373-4491-a51b-87d57d7aee9d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1165e53b-fcd8-45db-8842-0738a19a5b31</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/API/OPEN_WEATHER_MAP/test__search_weather_by_city</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>47d9c37b-92ce-45dc-bb22-dde6fd4c422a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4a6fec86-05db-4e9c-a658-a50e0ff7682a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a593e571-34a3-450d-b05b-571cf57fd340</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/API/OPEN_WEATHER_MAP/test__search_weather_by_city_not_found</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>91dc1bf1-0967-4710-a74b-83812d31c946</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a7906170-ef81-4aef-9059-e2f65da32837</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2625db62-dd4e-4601-9389-3967af6c301b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4f8d89f0-ebc1-427f-b5c0-a5c889569c87</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/API/OPEN_WEATHER_MAP/test__search_weather_by_city_without_appid</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bbafdf9d-3f56-4c55-ac29-dd5fccef5a3a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3e4a42e9-1c8f-4eb6-a468-921ba8ab3a37</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>91f49a28-c1dd-42aa-b38c-c86008ccf6c3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2ba54afb-2ec9-45d2-8391-faa805158c93</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/API/OPEN_WEATHER_MAP/test__search_weather_by_city_with_unsfafe_characters</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>18a3c306-9dcc-4151-9b16-b90a329b9805</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>47738b46-c067-4e75-9ca8-34c1ad6cd0c7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/API/OPEN_WEATHER_MAP/test__update_last_created_station_data</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>24435c09-d0d3-46c1-8a4e-ed5384651cf5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>51de0b33-0a4a-4656-9de0-f6a6b579d3ac</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>42777b16-b8e3-4388-9389-f61099dd1b88</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>749a036e-fce4-4913-9f6a-df8732fa6e94</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9686a901-54c0-46cf-929c-051c4e456a30</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>632160cd-1b9f-4062-b52f-889dee510cb8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ffb04d75-366b-41f7-b764-00152cb5b5ab</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/API/OPEN_WEATHER_MAP/test__station_crud</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>73547d5b-5e02-4918-93bf-6f0a4c808059</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>886b70e6-191f-42cf-bdab-3651a29b31e3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f1b2849d-9782-4433-9ded-f6b789a0e017</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0b92d379-f95c-492c-8682-756b4827e57f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>520f6ddb-0bec-4aba-bfc9-8473b558ed91</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4e46a325-3346-469d-bdfb-e999ff606682</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ad825384-93b7-42b2-87a1-f966c2e0db7e</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
