<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>error_login_id</name>
   <tag></tag>
   <elementGuidId>01a946db-c544-4dbb-94e6-d5707422cc9e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id=&quot;login_form&quot;][@data-status=&quot;step_1&quot;]//div[@id=&quot;login_id_container&quot;]//div[@id=&quot;error_login_id&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
