<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>password_container_label</name>
   <tag></tag>
   <elementGuidId>0a6b22f1-a273-4e89-b74e-bc8da6f62e28</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id=&quot;login_form&quot;][@data-status=&quot;step_2&quot;]//div[@id=&quot;login_password_container&quot;]/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
